runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /kisa-ki-di
    static_files: www/index.html
    upload: www/index.html

  - url: /kisa-ki-di/
    static_files: www/index.html
    upload: www/index.html

  - url: /kisa-ki-di/(.*\.(js|png|svg|css|gif))$
    static_files: www/\1
    upload: www/(.*)
